name: Run Script

on: 
  issues:
    types: [opened, labeled]

jobs:

  auto-reply:
  
    if: github.event.label.name == 'run_1'
    
    runs-on: ubuntu-latest

    permissions:
      issues: write
    
    steps:
    
      - name: Run Script
        run: echo "Hello world" | tee script-output.txt
        
      - name: Post Comment
        uses: actions/github-script@v3.1.0
        script: |
          const issue_number = context.issue.number;
          const scriptOutput = readFileSync('script-output.txt', 'utf8').trim();
          await github.issues.createComment({...context.repo, issue_number, body: scriptOutput});
